package main

// Autogenerated-equivalent port of confgenerator.c from VESC FW 6.05.
// Signature constants and field order match the C implementation exactly.

const (
	MCConfSignature  uint32 = 1065524471
	AppConfSignature uint32 = 2099347128
)

// MCConfiguration mirrors mc_configuration from VESC FW 6.05.
// Field order matches confgenerator_serialize_mcconf exactly.
type MCConfiguration struct {
	PwmMode    uint8
	CommMode   uint8
	MotorType  uint8
	SensorMode uint8

	LCurrentMax          float64
	LCurrentMin          float64
	LInCurrentMax        float64
	LInCurrentMin        float64
	LInCurrentMapStart   float64
	LInCurrentMapFilter  float64
	LAbsCurrentMax       float64
	LMinErpm             float64
	LMaxErpm             float64
	LErpmStart           float64
	LMaxErpmFbrake       float64
	LMaxErpmFbrakeCc     float64
	LMinVin              float64
	LMaxVin              float64
	LBatteryCutStart     float64
	LBatteryCutEnd       float64
	LBatteryRegenCutStart float64
	LBatteryRegenCutEnd  float64
	LSlowAbsCurrent      uint8
	LTempFetStart        uint8
	LTempFetEnd          uint8
	LTempMotorStart      uint8
	LTempMotorEnd        uint8
	LTempAccelDec        float64
	LMinDuty             float64
	LMaxDuty             float64
	LWattMax             float64
	LWattMin             float64
	LCurrentMaxScale     float64
	LCurrentMinScale     float64
	LDutyStart           float64

	SlMinErpm                        float64
	SlMinErpmCycleIntLimit           float64
	SlMaxFullbreakCurrentDirChange   float64
	SlCycleIntLimit                  float64
	SlPhaseAdvanceAtBr               float64
	SlCycleIntRpmBr                  float64
	SlBemfCouplingK                  float64

	HallTable  [8]uint8
	HallSlErpm float64

	FocCurrentKp          float64
	FocCurrentKi          float64
	FocFZv                float64
	FocDtUs               float64
	FocEncoderInverted    uint8
	FocEncoderOffset      float64
	FocEncoderRatio       float64
	FocSensorMode         uint8
	FocPllKp              float64
	FocPllKi              float64
	FocMotorL             float64
	FocMotorLdLqDiff      float64
	FocMotorR             float64
	FocMotorFluxLinkage   float64
	FocObserverGain       float64
	FocObserverGainSlow   float64
	FocObserverOffset     float64
	FocDutyDowmrampKp    float64
	FocDutyDowmrampKi    float64
	FocStartCurrDec       float64
	FocStartCurrDecRpm    float64
	FocOpenloopRpm        float64
	FocOpenloopRpmLow     float64
	FocDGainScaleStart    float64
	FocDGainScaleMaxMod   float64
	FocSlOpenloopHyst     float64
	FocSlOpenloopTimeLock float64
	FocSlOpenloopTimeRamp float64
	FocSlOpenloopTime     float64
	FocSlOpenloopBoostQ   float64
	FocSlOpenloopMaxQ     float64
	FocHallTable          [8]uint8
	FocHallInterpErpm     float64
	FocSlErpmStart        float64
	FocSlErpm             float64
	FocControlSampleMode  uint8
	FocCurrentSampleMode  uint8
	FocSatCompMode        uint8
	FocSatComp            float64
	FocTempComp           uint8
	FocTempCompBaseTemp   float64
	FocCurrentFilterConst float64
	FocCcDecoupling       uint8
	FocObserverType       uint8
	FocHfiVoltageStart    float64
	FocHfiVoltageRun      float64
	FocHfiVoltageMax      float64
	FocHfiGain            float64
	FocHfiMaxErr          float64
	FocHfiHyst            float64
	FocSlErpmHfi          float64
	FocHfiStartSamples    uint16
	FocHfiObsOvrSec       float64
	FocHfiSamples         uint8
	FocOffsetsCalOnBoot   uint8
	FocOffsetsCurrent     [3]float64
	FocOffsetsVoltage     [3]float64
	FocOffsetsVoltageUndriven [3]float64
	FocPhaseFilterEnable       uint8
	FocPhaseFilterDisableFault uint8
	FocPhaseFilterMaxErpm      float64
	FocMtpaMode                uint8
	FocFwCurrentMax            float64
	FocFwDutyStart             float64
	FocFwRampTime              float64
	FocFwQCurrentFactor        float64
	FocSpeedSoure              uint8 // note: typo preserved from C source
	FocShortLsOnZeroDuty       uint8

	SpPidLoopRate   uint8
	SPidKp          float64
	SPidKi          float64
	SPidKd          float64
	SPidKdFilter    float64
	SPidMinErpm     float64
	SPidAllowBraking uint8
	SPidRampErpmsS  float64
	SPidSpeedSource uint8

	PPidKp           float64
	PPidKi           float64
	PPidKd           float64
	PPidKdProc       float64
	PPidKdFilter     float64
	PPidAngDiv       float64
	PPidGainDecAngle float64
	PPidOffset       float64

	CcStartupBoostDuty float64
	CcMinCurrent       float64
	CcGain             float64
	CcRampStepMax      float64

	MFaultStopTimeMs              int32
	MDutyRampStep                 float64
	MCurrentBackoffGain           float64
	MEncoderCounts                uint32
	MEncoderSinAmp                float64
	MEncoderCosAmp                float64
	MEncoderSinOffset             float64
	MEncoderCosOffset             float64
	MEncoderSincosFilterConstant  float64
	MEncoderSincosPhaseCorrection float64
	MSensorPortMode               uint8
	MInvertDirection              uint8
	MDrv8301OcMode                uint8
	MDrv8301OcAdj                 uint8
	MBldcFSwMin                   float64
	MBldcFSwMax                   float64
	MDcFSw                        float64
	MNtcMotorBeta                 float64
	MOutAuxMode                   uint8
	MMotorTempSensType            uint8
	MPtcMotorCoeff                float64
	MNtcxPtcxRes                  float64
	MNtcxPtcxTempBase             float64
	MHallExtraSamples             uint8
	MBattFilterConst              uint8

	SiMotorPoles   uint8
	SiGearRatio    float64
	SiWheelDiameter float64
	SiBatteryType  uint8
	SiBatteryCells uint8
	SiBatteryAh    float64
	SiMotorNlCurrent float64

	BmsType          uint8
	BmsLimitMode     uint8
	BmsTLimitStart   uint8
	BmsTLimitEnd     uint8
	BmsSocLimitStart float64
	BmsSocLimitEnd   float64
	BmsVminLimitStart float64
	BmsVminLimitEnd  float64
	BmsVmaxLimitStart float64
	BmsVmaxLimitEnd  float64
	BmsFwdCanMode    uint8
}

// PPMConfiguration mirrors ppm_config from VESC FW 6.05.
type PPMConfiguration struct {
	CtrlType         uint8
	PidMaxErpm       float64
	Hyst             float64
	PulseStart       float64
	PulseEnd         float64
	PulseCenter      float64
	MedianFilter     uint8
	SafeStart        uint8
	ThrottleExp      float64
	ThrottleExpBrake float64
	ThrottleExpMode  uint8
	RampTimePos      float64
	RampTimeNeg      float64
	MultiEsc         uint8
	Tc               uint8
	TcMaxDiff        float64
	MaxErpmForDir    float64
	SmartRevMaxDuty  float64
	SmartRevRampTime float64
}

// ADCConfiguration mirrors adc_config from VESC FW 6.05.
type ADCConfiguration struct {
	CtrlType         uint8
	Hyst             float64
	VoltageStart     float64
	VoltageEnd       float64
	VoltageMin       float64
	VoltageMax       float64
	VoltageCenter    float64
	Voltage2Start    float64
	Voltage2End      float64
	UseFilter        uint8
	SafeStart        uint8
	Buttons          uint8
	VoltageInverted  uint8
	Voltage2Inverted uint8
	ThrottleExp      float64
	ThrottleExpBrake float64
	ThrottleExpMode  uint8
	RampTimePos      float64
	RampTimeNeg      float64
	MultiEsc         uint8
	Tc               uint8
	TcMaxDiff        float64
	UpdateRateHz     uint16
}

// ChukConfiguration mirrors chuk_config from VESC FW 6.05.
type ChukConfiguration struct {
	CtrlType           uint8
	Hyst               float64
	RampTimePos        float64
	RampTimeNeg        float64
	StickErpmPerSInCc  float64
	ThrottleExp        float64
	ThrottleExpBrake   float64
	ThrottleExpMode    uint8
	MultiEsc           uint8
	Tc                 uint8
	TcMaxDiff          float64
	UseSmartRev        uint8
	SmartRevMaxDuty    float64
	SmartRevRampTime   float64
}

// NRFConfiguration mirrors nrf_config from VESC FW 6.05.
type NRFConfiguration struct {
	Speed      uint8
	Power      uint8
	CrcType    uint8
	RetryDelay uint8
	Retries    uint8
	Channel    uint8
	Address    [3]uint8
	SendCrcAck uint8
}

// PASConfiguration mirrors pas_config from VESC FW 6.05.
type PASConfiguration struct {
	CtrlType              uint8
	SensorType            uint8
	CurrentScaling        float64
	PedalRpmStart         float64
	PedalRpmEnd           float64
	InvertPedalDirection  uint8
	Magnets               uint16
	UseFilter             uint8
	RampTimePos           float64
	RampTimeNeg           float64
	UpdateRateHz          uint16
}

// IMUConfiguration mirrors imu_config from VESC FW 6.05.
type IMUConfiguration struct {
	Type                   uint8
	Mode                   uint8
	Filter                 uint8
	AccelLowpassFilterX    float64
	AccelLowpassFilterY    float64
	AccelLowpassFilterZ    float64
	GyroLowpassFilter      float64
	SampleRateHz           uint16
	UseMagnetometer        uint8
	AccelConfidenceDecay   float64
	MahonyKp               float64
	MahonyKi               float64
	MadgwickBeta           float64
	RotRoll                float64
	RotPitch               float64
	RotYaw                 float64
	AccelOffsets           [3]float64
	GyroOffsets            [3]float64
}

// AppConfiguration mirrors app_configuration from VESC FW 6.05.
// Field order matches confgenerator_serialize_appconf exactly.
type AppConfiguration struct {
	ControllerId          uint8
	TimeoutMsec           uint32
	TimeoutBrakeCurrent   float64
	CanStatusRate1        uint16
	CanStatusRate2        uint16
	CanStatusMsgsR1       uint8
	CanStatusMsgsR2       uint8
	CanBaudRate           uint8
	PairingDone           uint8
	PermanentUartEnabled  uint8
	ShutdownMode          uint8
	CanMode               uint8
	UavcanEscIndex        uint8
	UavcanRawMode         uint8
	UavcanRawRpmMax       float64
	UavcanStatusCurrentMode uint8
	ServoOutEnable        uint8
	KillSwMode            uint8
	AppToUse              uint8
	AppPpmConf            PPMConfiguration
	AppAdcConf            ADCConfiguration
	AppUartBaudrate       uint32
	AppChukConf           ChukConfiguration
	AppNrfConf            NRFConfiguration
	AppPasConf            PASConfiguration
	ImuConf               IMUConfiguration
}

// SerializeMCConf serializes an MCConfiguration to bytes, matching the C
// confgenerator_serialize_mcconf function byte-for-byte.
func SerializeMCConf(conf *MCConfiguration) []byte {
	buf := make([]byte, 0, 512)

	buf = AppendUint32(buf, MCConfSignature)

	buf = append(buf, conf.PwmMode)
	buf = append(buf, conf.CommMode)
	buf = append(buf, conf.MotorType)
	buf = append(buf, conf.SensorMode)
	buf = AppendFloat32Auto(buf, conf.LCurrentMax)
	buf = AppendFloat32Auto(buf, conf.LCurrentMin)
	buf = AppendFloat32Auto(buf, conf.LInCurrentMax)
	buf = AppendFloat32Auto(buf, conf.LInCurrentMin)
	buf = AppendFloat16(buf, conf.LInCurrentMapStart, 10000)
	buf = AppendFloat16(buf, conf.LInCurrentMapFilter, 10000)
	buf = AppendFloat32Auto(buf, conf.LAbsCurrentMax)
	buf = AppendFloat32Auto(buf, conf.LMinErpm)
	buf = AppendFloat32Auto(buf, conf.LMaxErpm)
	buf = AppendFloat16(buf, conf.LErpmStart, 10000)
	buf = AppendFloat32Auto(buf, conf.LMaxErpmFbrake)
	buf = AppendFloat32Auto(buf, conf.LMaxErpmFbrakeCc)
	buf = AppendFloat16(buf, conf.LMinVin, 10)
	buf = AppendFloat16(buf, conf.LMaxVin, 10)
	buf = AppendFloat16(buf, conf.LBatteryCutStart, 10)
	buf = AppendFloat16(buf, conf.LBatteryCutEnd, 10)
	buf = AppendFloat16(buf, conf.LBatteryRegenCutStart, 10)
	buf = AppendFloat16(buf, conf.LBatteryRegenCutEnd, 10)
	buf = append(buf, conf.LSlowAbsCurrent)
	buf = append(buf, conf.LTempFetStart)
	buf = append(buf, conf.LTempFetEnd)
	buf = append(buf, conf.LTempMotorStart)
	buf = append(buf, conf.LTempMotorEnd)
	buf = AppendFloat16(buf, conf.LTempAccelDec, 10000)
	buf = AppendFloat16(buf, conf.LMinDuty, 10000)
	buf = AppendFloat16(buf, conf.LMaxDuty, 10000)
	buf = AppendFloat32Auto(buf, conf.LWattMax)
	buf = AppendFloat32Auto(buf, conf.LWattMin)
	buf = AppendFloat16(buf, conf.LCurrentMaxScale, 10000)
	buf = AppendFloat16(buf, conf.LCurrentMinScale, 10000)
	buf = AppendFloat16(buf, conf.LDutyStart, 10000)
	buf = AppendFloat32Auto(buf, conf.SlMinErpm)
	buf = AppendFloat32Auto(buf, conf.SlMinErpmCycleIntLimit)
	buf = AppendFloat32Auto(buf, conf.SlMaxFullbreakCurrentDirChange)
	buf = AppendFloat16(buf, conf.SlCycleIntLimit, 10)
	buf = AppendFloat16(buf, conf.SlPhaseAdvanceAtBr, 10000)
	buf = AppendFloat32Auto(buf, conf.SlCycleIntRpmBr)
	buf = AppendFloat32Auto(buf, conf.SlBemfCouplingK)
	for i := 0; i < 8; i++ {
		buf = append(buf, conf.HallTable[i])
	}
	buf = AppendFloat32Auto(buf, conf.HallSlErpm)
	buf = AppendFloat32Auto(buf, conf.FocCurrentKp)
	buf = AppendFloat32Auto(buf, conf.FocCurrentKi)
	buf = AppendFloat32Auto(buf, conf.FocFZv)
	buf = AppendFloat32Auto(buf, conf.FocDtUs)
	buf = append(buf, conf.FocEncoderInverted)
	buf = AppendFloat32Auto(buf, conf.FocEncoderOffset)
	buf = AppendFloat32Auto(buf, conf.FocEncoderRatio)
	buf = append(buf, conf.FocSensorMode)
	buf = AppendFloat32Auto(buf, conf.FocPllKp)
	buf = AppendFloat32Auto(buf, conf.FocPllKi)
	buf = AppendFloat32Auto(buf, conf.FocMotorL)
	buf = AppendFloat32Auto(buf, conf.FocMotorLdLqDiff)
	buf = AppendFloat32Auto(buf, conf.FocMotorR)
	buf = AppendFloat32Auto(buf, conf.FocMotorFluxLinkage)
	buf = AppendFloat32Auto(buf, conf.FocObserverGain)
	buf = AppendFloat32Auto(buf, conf.FocObserverGainSlow)
	buf = AppendFloat16(buf, conf.FocObserverOffset, 1000)
	buf = AppendFloat32Auto(buf, conf.FocDutyDowmrampKp)
	buf = AppendFloat32Auto(buf, conf.FocDutyDowmrampKi)
	buf = AppendFloat16(buf, conf.FocStartCurrDec, 10000)
	buf = AppendFloat32Auto(buf, conf.FocStartCurrDecRpm)
	buf = AppendFloat32Auto(buf, conf.FocOpenloopRpm)
	buf = AppendFloat16(buf, conf.FocOpenloopRpmLow, 1000)
	buf = AppendFloat16(buf, conf.FocDGainScaleStart, 1000)
	buf = AppendFloat16(buf, conf.FocDGainScaleMaxMod, 1000)
	buf = AppendFloat16(buf, conf.FocSlOpenloopHyst, 100)
	buf = AppendFloat16(buf, conf.FocSlOpenloopTimeLock, 100)
	buf = AppendFloat16(buf, conf.FocSlOpenloopTimeRamp, 100)
	buf = AppendFloat16(buf, conf.FocSlOpenloopTime, 100)
	buf = AppendFloat16(buf, conf.FocSlOpenloopBoostQ, 100)
	buf = AppendFloat16(buf, conf.FocSlOpenloopMaxQ, 100)
	for i := 0; i < 8; i++ {
		buf = append(buf, conf.FocHallTable[i])
	}
	buf = AppendFloat32Auto(buf, conf.FocHallInterpErpm)
	buf = AppendFloat32Auto(buf, conf.FocSlErpmStart)
	buf = AppendFloat32Auto(buf, conf.FocSlErpm)
	buf = append(buf, conf.FocControlSampleMode)
	buf = append(buf, conf.FocCurrentSampleMode)
	buf = append(buf, conf.FocSatCompMode)
	buf = AppendFloat16(buf, conf.FocSatComp, 1000)
	buf = append(buf, conf.FocTempComp)
	buf = AppendFloat16(buf, conf.FocTempCompBaseTemp, 100)
	buf = AppendFloat16(buf, conf.FocCurrentFilterConst, 10000)
	buf = append(buf, conf.FocCcDecoupling)
	buf = append(buf, conf.FocObserverType)
	buf = AppendFloat16(buf, conf.FocHfiVoltageStart, 10)
	buf = AppendFloat16(buf, conf.FocHfiVoltageRun, 10)
	buf = AppendFloat16(buf, conf.FocHfiVoltageMax, 10)
	buf = AppendFloat16(buf, conf.FocHfiGain, 1000)
	buf = AppendFloat16(buf, conf.FocHfiMaxErr, 1000)
	buf = AppendFloat16(buf, conf.FocHfiHyst, 100)
	buf = AppendFloat32Auto(buf, conf.FocSlErpmHfi)
	buf = AppendUint16(buf, conf.FocHfiStartSamples)
	buf = AppendFloat32Auto(buf, conf.FocHfiObsOvrSec)
	buf = append(buf, conf.FocHfiSamples)
	buf = append(buf, conf.FocOffsetsCalOnBoot)
	buf = AppendFloat32Auto(buf, conf.FocOffsetsCurrent[0])
	buf = AppendFloat32Auto(buf, conf.FocOffsetsCurrent[1])
	buf = AppendFloat32Auto(buf, conf.FocOffsetsCurrent[2])
	buf = AppendFloat16(buf, conf.FocOffsetsVoltage[0], 10000)
	buf = AppendFloat16(buf, conf.FocOffsetsVoltage[1], 10000)
	buf = AppendFloat16(buf, conf.FocOffsetsVoltage[2], 10000)
	buf = AppendFloat16(buf, conf.FocOffsetsVoltageUndriven[0], 10000)
	buf = AppendFloat16(buf, conf.FocOffsetsVoltageUndriven[1], 10000)
	buf = AppendFloat16(buf, conf.FocOffsetsVoltageUndriven[2], 10000)
	buf = append(buf, conf.FocPhaseFilterEnable)
	buf = append(buf, conf.FocPhaseFilterDisableFault)
	buf = AppendFloat32Auto(buf, conf.FocPhaseFilterMaxErpm)
	buf = append(buf, conf.FocMtpaMode)
	buf = AppendFloat32Auto(buf, conf.FocFwCurrentMax)
	buf = AppendFloat16(buf, conf.FocFwDutyStart, 10000)
	buf = AppendFloat16(buf, conf.FocFwRampTime, 1000)
	buf = AppendFloat16(buf, conf.FocFwQCurrentFactor, 10000)
	buf = append(buf, conf.FocSpeedSoure)
	buf = append(buf, conf.FocShortLsOnZeroDuty)
	buf = append(buf, conf.SpPidLoopRate)
	buf = AppendFloat32Auto(buf, conf.SPidKp)
	buf = AppendFloat32Auto(buf, conf.SPidKi)
	buf = AppendFloat32Auto(buf, conf.SPidKd)
	buf = AppendFloat16(buf, conf.SPidKdFilter, 10000)
	buf = AppendFloat32Auto(buf, conf.SPidMinErpm)
	buf = append(buf, conf.SPidAllowBraking)
	buf = AppendFloat32Auto(buf, conf.SPidRampErpmsS)
	buf = append(buf, conf.SPidSpeedSource)
	buf = AppendFloat32Auto(buf, conf.PPidKp)
	buf = AppendFloat32Auto(buf, conf.PPidKi)
	buf = AppendFloat32Auto(buf, conf.PPidKd)
	buf = AppendFloat32Auto(buf, conf.PPidKdProc)
	buf = AppendFloat16(buf, conf.PPidKdFilter, 10000)
	buf = AppendFloat32Auto(buf, conf.PPidAngDiv)
	buf = AppendFloat16(buf, conf.PPidGainDecAngle, 10)
	buf = AppendFloat32Auto(buf, conf.PPidOffset)
	buf = AppendFloat16(buf, conf.CcStartupBoostDuty, 10000)
	buf = AppendFloat32Auto(buf, conf.CcMinCurrent)
	buf = AppendFloat32Auto(buf, conf.CcGain)
	buf = AppendFloat16(buf, conf.CcRampStepMax, 10000)
	buf = AppendInt32(buf, conf.MFaultStopTimeMs)
	buf = AppendFloat16(buf, conf.MDutyRampStep, 10000)
	buf = AppendFloat32Auto(buf, conf.MCurrentBackoffGain)
	buf = AppendUint32(buf, conf.MEncoderCounts)
	buf = AppendFloat16(buf, conf.MEncoderSinAmp, 1000)
	buf = AppendFloat16(buf, conf.MEncoderCosAmp, 1000)
	buf = AppendFloat16(buf, conf.MEncoderSinOffset, 1000)
	buf = AppendFloat16(buf, conf.MEncoderCosOffset, 1000)
	buf = AppendFloat16(buf, conf.MEncoderSincosFilterConstant, 1000)
	buf = AppendFloat16(buf, conf.MEncoderSincosPhaseCorrection, 1000)
	buf = append(buf, conf.MSensorPortMode)
	buf = append(buf, conf.MInvertDirection)
	buf = append(buf, conf.MDrv8301OcMode)
	buf = append(buf, conf.MDrv8301OcAdj)
	buf = AppendFloat32Auto(buf, conf.MBldcFSwMin)
	buf = AppendFloat32Auto(buf, conf.MBldcFSwMax)
	buf = AppendFloat32Auto(buf, conf.MDcFSw)
	buf = AppendFloat32Auto(buf, conf.MNtcMotorBeta)
	buf = append(buf, conf.MOutAuxMode)
	buf = append(buf, conf.MMotorTempSensType)
	buf = AppendFloat32Auto(buf, conf.MPtcMotorCoeff)
	buf = AppendFloat16(buf, conf.MNtcxPtcxRes, 0.1)
	buf = AppendFloat16(buf, conf.MNtcxPtcxTempBase, 10)
	buf = append(buf, conf.MHallExtraSamples)
	buf = append(buf, conf.MBattFilterConst)
	buf = append(buf, conf.SiMotorPoles)
	buf = AppendFloat32Auto(buf, conf.SiGearRatio)
	buf = AppendFloat32Auto(buf, conf.SiWheelDiameter)
	buf = append(buf, conf.SiBatteryType)
	buf = append(buf, conf.SiBatteryCells)
	buf = AppendFloat32Auto(buf, conf.SiBatteryAh)
	buf = AppendFloat32Auto(buf, conf.SiMotorNlCurrent)
	buf = append(buf, conf.BmsType)
	buf = append(buf, conf.BmsLimitMode)
	buf = append(buf, conf.BmsTLimitStart)
	buf = append(buf, conf.BmsTLimitEnd)
	buf = AppendFloat16(buf, conf.BmsSocLimitStart, 1000)
	buf = AppendFloat16(buf, conf.BmsSocLimitEnd, 1000)
	buf = AppendFloat16(buf, conf.BmsVminLimitStart, 1000)
	buf = AppendFloat16(buf, conf.BmsVminLimitEnd, 1000)
	buf = AppendFloat16(buf, conf.BmsVmaxLimitStart, 1000)
	buf = AppendFloat16(buf, conf.BmsVmaxLimitEnd, 1000)
	buf = append(buf, conf.BmsFwdCanMode)

	return buf
}

// DeserializeMCConf deserializes an MCConfiguration from bytes, matching the C
// confgenerator_deserialize_mcconf function exactly.
func DeserializeMCConf(buf []byte) (*MCConfiguration, bool) {
	if len(buf) < 4 {
		return nil, false
	}
	ind := 0
	sig := GetUint32(buf, &ind)
	if sig != MCConfSignature {
		return nil, false
	}

	conf := &MCConfiguration{}
	conf.PwmMode = buf[ind]; ind++
	conf.CommMode = buf[ind]; ind++
	conf.MotorType = buf[ind]; ind++
	conf.SensorMode = buf[ind]; ind++
	conf.LCurrentMax = GetFloat32Auto(buf, &ind)
	conf.LCurrentMin = GetFloat32Auto(buf, &ind)
	conf.LInCurrentMax = GetFloat32Auto(buf, &ind)
	conf.LInCurrentMin = GetFloat32Auto(buf, &ind)
	conf.LInCurrentMapStart = GetFloat16(buf, 10000, &ind)
	conf.LInCurrentMapFilter = GetFloat16(buf, 10000, &ind)
	conf.LAbsCurrentMax = GetFloat32Auto(buf, &ind)
	conf.LMinErpm = GetFloat32Auto(buf, &ind)
	conf.LMaxErpm = GetFloat32Auto(buf, &ind)
	conf.LErpmStart = GetFloat16(buf, 10000, &ind)
	conf.LMaxErpmFbrake = GetFloat32Auto(buf, &ind)
	conf.LMaxErpmFbrakeCc = GetFloat32Auto(buf, &ind)
	conf.LMinVin = GetFloat16(buf, 10, &ind)
	conf.LMaxVin = GetFloat16(buf, 10, &ind)
	conf.LBatteryCutStart = GetFloat16(buf, 10, &ind)
	conf.LBatteryCutEnd = GetFloat16(buf, 10, &ind)
	conf.LBatteryRegenCutStart = GetFloat16(buf, 10, &ind)
	conf.LBatteryRegenCutEnd = GetFloat16(buf, 10, &ind)
	conf.LSlowAbsCurrent = buf[ind]; ind++
	conf.LTempFetStart = buf[ind]; ind++
	conf.LTempFetEnd = buf[ind]; ind++
	conf.LTempMotorStart = buf[ind]; ind++
	conf.LTempMotorEnd = buf[ind]; ind++
	conf.LTempAccelDec = GetFloat16(buf, 10000, &ind)
	conf.LMinDuty = GetFloat16(buf, 10000, &ind)
	conf.LMaxDuty = GetFloat16(buf, 10000, &ind)
	conf.LWattMax = GetFloat32Auto(buf, &ind)
	conf.LWattMin = GetFloat32Auto(buf, &ind)
	conf.LCurrentMaxScale = GetFloat16(buf, 10000, &ind)
	conf.LCurrentMinScale = GetFloat16(buf, 10000, &ind)
	conf.LDutyStart = GetFloat16(buf, 10000, &ind)
	conf.SlMinErpm = GetFloat32Auto(buf, &ind)
	conf.SlMinErpmCycleIntLimit = GetFloat32Auto(buf, &ind)
	conf.SlMaxFullbreakCurrentDirChange = GetFloat32Auto(buf, &ind)
	conf.SlCycleIntLimit = GetFloat16(buf, 10, &ind)
	conf.SlPhaseAdvanceAtBr = GetFloat16(buf, 10000, &ind)
	conf.SlCycleIntRpmBr = GetFloat32Auto(buf, &ind)
	conf.SlBemfCouplingK = GetFloat32Auto(buf, &ind)
	for i := 0; i < 8; i++ {
		conf.HallTable[i] = buf[ind]; ind++
	}
	conf.HallSlErpm = GetFloat32Auto(buf, &ind)
	conf.FocCurrentKp = GetFloat32Auto(buf, &ind)
	conf.FocCurrentKi = GetFloat32Auto(buf, &ind)
	conf.FocFZv = GetFloat32Auto(buf, &ind)
	conf.FocDtUs = GetFloat32Auto(buf, &ind)
	conf.FocEncoderInverted = buf[ind]; ind++
	conf.FocEncoderOffset = GetFloat32Auto(buf, &ind)
	conf.FocEncoderRatio = GetFloat32Auto(buf, &ind)
	conf.FocSensorMode = buf[ind]; ind++
	conf.FocPllKp = GetFloat32Auto(buf, &ind)
	conf.FocPllKi = GetFloat32Auto(buf, &ind)
	conf.FocMotorL = GetFloat32Auto(buf, &ind)
	conf.FocMotorLdLqDiff = GetFloat32Auto(buf, &ind)
	conf.FocMotorR = GetFloat32Auto(buf, &ind)
	conf.FocMotorFluxLinkage = GetFloat32Auto(buf, &ind)
	conf.FocObserverGain = GetFloat32Auto(buf, &ind)
	conf.FocObserverGainSlow = GetFloat32Auto(buf, &ind)
	conf.FocObserverOffset = GetFloat16(buf, 1000, &ind)
	conf.FocDutyDowmrampKp = GetFloat32Auto(buf, &ind)
	conf.FocDutyDowmrampKi = GetFloat32Auto(buf, &ind)
	conf.FocStartCurrDec = GetFloat16(buf, 10000, &ind)
	conf.FocStartCurrDecRpm = GetFloat32Auto(buf, &ind)
	conf.FocOpenloopRpm = GetFloat32Auto(buf, &ind)
	conf.FocOpenloopRpmLow = GetFloat16(buf, 1000, &ind)
	conf.FocDGainScaleStart = GetFloat16(buf, 1000, &ind)
	conf.FocDGainScaleMaxMod = GetFloat16(buf, 1000, &ind)
	conf.FocSlOpenloopHyst = GetFloat16(buf, 100, &ind)
	conf.FocSlOpenloopTimeLock = GetFloat16(buf, 100, &ind)
	conf.FocSlOpenloopTimeRamp = GetFloat16(buf, 100, &ind)
	conf.FocSlOpenloopTime = GetFloat16(buf, 100, &ind)
	conf.FocSlOpenloopBoostQ = GetFloat16(buf, 100, &ind)
	conf.FocSlOpenloopMaxQ = GetFloat16(buf, 100, &ind)
	for i := 0; i < 8; i++ {
		conf.FocHallTable[i] = buf[ind]; ind++
	}
	conf.FocHallInterpErpm = GetFloat32Auto(buf, &ind)
	conf.FocSlErpmStart = GetFloat32Auto(buf, &ind)
	conf.FocSlErpm = GetFloat32Auto(buf, &ind)
	conf.FocControlSampleMode = buf[ind]; ind++
	conf.FocCurrentSampleMode = buf[ind]; ind++
	conf.FocSatCompMode = buf[ind]; ind++
	conf.FocSatComp = GetFloat16(buf, 1000, &ind)
	conf.FocTempComp = buf[ind]; ind++
	conf.FocTempCompBaseTemp = GetFloat16(buf, 100, &ind)
	conf.FocCurrentFilterConst = GetFloat16(buf, 10000, &ind)
	conf.FocCcDecoupling = buf[ind]; ind++
	conf.FocObserverType = buf[ind]; ind++
	conf.FocHfiVoltageStart = GetFloat16(buf, 10, &ind)
	conf.FocHfiVoltageRun = GetFloat16(buf, 10, &ind)
	conf.FocHfiVoltageMax = GetFloat16(buf, 10, &ind)
	conf.FocHfiGain = GetFloat16(buf, 1000, &ind)
	conf.FocHfiMaxErr = GetFloat16(buf, 1000, &ind)
	conf.FocHfiHyst = GetFloat16(buf, 100, &ind)
	conf.FocSlErpmHfi = GetFloat32Auto(buf, &ind)
	conf.FocHfiStartSamples = GetUint16(buf, &ind)
	conf.FocHfiObsOvrSec = GetFloat32Auto(buf, &ind)
	conf.FocHfiSamples = buf[ind]; ind++
	conf.FocOffsetsCalOnBoot = buf[ind]; ind++
	conf.FocOffsetsCurrent[0] = GetFloat32Auto(buf, &ind)
	conf.FocOffsetsCurrent[1] = GetFloat32Auto(buf, &ind)
	conf.FocOffsetsCurrent[2] = GetFloat32Auto(buf, &ind)
	conf.FocOffsetsVoltage[0] = GetFloat16(buf, 10000, &ind)
	conf.FocOffsetsVoltage[1] = GetFloat16(buf, 10000, &ind)
	conf.FocOffsetsVoltage[2] = GetFloat16(buf, 10000, &ind)
	conf.FocOffsetsVoltageUndriven[0] = GetFloat16(buf, 10000, &ind)
	conf.FocOffsetsVoltageUndriven[1] = GetFloat16(buf, 10000, &ind)
	conf.FocOffsetsVoltageUndriven[2] = GetFloat16(buf, 10000, &ind)
	conf.FocPhaseFilterEnable = buf[ind]; ind++
	conf.FocPhaseFilterDisableFault = buf[ind]; ind++
	conf.FocPhaseFilterMaxErpm = GetFloat32Auto(buf, &ind)
	conf.FocMtpaMode = buf[ind]; ind++
	conf.FocFwCurrentMax = GetFloat32Auto(buf, &ind)
	conf.FocFwDutyStart = GetFloat16(buf, 10000, &ind)
	conf.FocFwRampTime = GetFloat16(buf, 1000, &ind)
	conf.FocFwQCurrentFactor = GetFloat16(buf, 10000, &ind)
	conf.FocSpeedSoure = buf[ind]; ind++
	conf.FocShortLsOnZeroDuty = buf[ind]; ind++
	conf.SpPidLoopRate = buf[ind]; ind++
	conf.SPidKp = GetFloat32Auto(buf, &ind)
	conf.SPidKi = GetFloat32Auto(buf, &ind)
	conf.SPidKd = GetFloat32Auto(buf, &ind)
	conf.SPidKdFilter = GetFloat16(buf, 10000, &ind)
	conf.SPidMinErpm = GetFloat32Auto(buf, &ind)
	conf.SPidAllowBraking = buf[ind]; ind++
	conf.SPidRampErpmsS = GetFloat32Auto(buf, &ind)
	conf.SPidSpeedSource = buf[ind]; ind++
	conf.PPidKp = GetFloat32Auto(buf, &ind)
	conf.PPidKi = GetFloat32Auto(buf, &ind)
	conf.PPidKd = GetFloat32Auto(buf, &ind)
	conf.PPidKdProc = GetFloat32Auto(buf, &ind)
	conf.PPidKdFilter = GetFloat16(buf, 10000, &ind)
	conf.PPidAngDiv = GetFloat32Auto(buf, &ind)
	conf.PPidGainDecAngle = GetFloat16(buf, 10, &ind)
	conf.PPidOffset = GetFloat32Auto(buf, &ind)
	conf.CcStartupBoostDuty = GetFloat16(buf, 10000, &ind)
	conf.CcMinCurrent = GetFloat32Auto(buf, &ind)
	conf.CcGain = GetFloat32Auto(buf, &ind)
	conf.CcRampStepMax = GetFloat16(buf, 10000, &ind)
	conf.MFaultStopTimeMs = GetInt32(buf, &ind)
	conf.MDutyRampStep = GetFloat16(buf, 10000, &ind)
	conf.MCurrentBackoffGain = GetFloat32Auto(buf, &ind)
	conf.MEncoderCounts = GetUint32(buf, &ind)
	conf.MEncoderSinAmp = GetFloat16(buf, 1000, &ind)
	conf.MEncoderCosAmp = GetFloat16(buf, 1000, &ind)
	conf.MEncoderSinOffset = GetFloat16(buf, 1000, &ind)
	conf.MEncoderCosOffset = GetFloat16(buf, 1000, &ind)
	conf.MEncoderSincosFilterConstant = GetFloat16(buf, 1000, &ind)
	conf.MEncoderSincosPhaseCorrection = GetFloat16(buf, 1000, &ind)
	conf.MSensorPortMode = buf[ind]; ind++
	conf.MInvertDirection = buf[ind]; ind++
	conf.MDrv8301OcMode = buf[ind]; ind++
	conf.MDrv8301OcAdj = buf[ind]; ind++
	conf.MBldcFSwMin = GetFloat32Auto(buf, &ind)
	conf.MBldcFSwMax = GetFloat32Auto(buf, &ind)
	conf.MDcFSw = GetFloat32Auto(buf, &ind)
	conf.MNtcMotorBeta = GetFloat32Auto(buf, &ind)
	conf.MOutAuxMode = buf[ind]; ind++
	conf.MMotorTempSensType = buf[ind]; ind++
	conf.MPtcMotorCoeff = GetFloat32Auto(buf, &ind)
	conf.MNtcxPtcxRes = GetFloat16(buf, 0.1, &ind)
	conf.MNtcxPtcxTempBase = GetFloat16(buf, 10, &ind)
	conf.MHallExtraSamples = buf[ind]; ind++
	conf.MBattFilterConst = buf[ind]; ind++
	conf.SiMotorPoles = buf[ind]; ind++
	conf.SiGearRatio = GetFloat32Auto(buf, &ind)
	conf.SiWheelDiameter = GetFloat32Auto(buf, &ind)
	conf.SiBatteryType = buf[ind]; ind++
	conf.SiBatteryCells = buf[ind]; ind++
	conf.SiBatteryAh = GetFloat32Auto(buf, &ind)
	conf.SiMotorNlCurrent = GetFloat32Auto(buf, &ind)
	conf.BmsType = buf[ind]; ind++
	conf.BmsLimitMode = buf[ind]; ind++
	conf.BmsTLimitStart = buf[ind]; ind++
	conf.BmsTLimitEnd = buf[ind]; ind++
	conf.BmsSocLimitStart = GetFloat16(buf, 1000, &ind)
	conf.BmsSocLimitEnd = GetFloat16(buf, 1000, &ind)
	conf.BmsVminLimitStart = GetFloat16(buf, 1000, &ind)
	conf.BmsVminLimitEnd = GetFloat16(buf, 1000, &ind)
	conf.BmsVmaxLimitStart = GetFloat16(buf, 1000, &ind)
	conf.BmsVmaxLimitEnd = GetFloat16(buf, 1000, &ind)
	conf.BmsFwdCanMode = buf[ind]; ind++

	return conf, true
}

// SerializeAppConf serializes an AppConfiguration to bytes, matching the C
// confgenerator_serialize_appconf function byte-for-byte.
func SerializeAppConf(conf *AppConfiguration) []byte {
	buf := make([]byte, 0, 512)

	buf = AppendUint32(buf, AppConfSignature)

	buf = append(buf, conf.ControllerId)
	buf = AppendUint32(buf, conf.TimeoutMsec)
	buf = AppendFloat32Auto(buf, conf.TimeoutBrakeCurrent)
	buf = AppendUint16(buf, conf.CanStatusRate1)
	buf = AppendUint16(buf, conf.CanStatusRate2)
	buf = append(buf, conf.CanStatusMsgsR1)
	buf = append(buf, conf.CanStatusMsgsR2)
	buf = append(buf, conf.CanBaudRate)
	buf = append(buf, conf.PairingDone)
	buf = append(buf, conf.PermanentUartEnabled)
	buf = append(buf, conf.ShutdownMode)
	buf = append(buf, conf.CanMode)
	buf = append(buf, conf.UavcanEscIndex)
	buf = append(buf, conf.UavcanRawMode)
	buf = AppendFloat32Auto(buf, conf.UavcanRawRpmMax)
	buf = append(buf, conf.UavcanStatusCurrentMode)
	buf = append(buf, conf.ServoOutEnable)
	buf = append(buf, conf.KillSwMode)
	buf = append(buf, conf.AppToUse)
	// PPM
	buf = append(buf, conf.AppPpmConf.CtrlType)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.PidMaxErpm)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.Hyst)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.PulseStart)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.PulseEnd)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.PulseCenter)
	buf = append(buf, conf.AppPpmConf.MedianFilter)
	buf = append(buf, conf.AppPpmConf.SafeStart)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.ThrottleExp)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.ThrottleExpBrake)
	buf = append(buf, conf.AppPpmConf.ThrottleExpMode)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.RampTimePos)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.RampTimeNeg)
	buf = append(buf, conf.AppPpmConf.MultiEsc)
	buf = append(buf, conf.AppPpmConf.Tc)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.TcMaxDiff)
	buf = AppendFloat16(buf, conf.AppPpmConf.MaxErpmForDir, 1)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.SmartRevMaxDuty)
	buf = AppendFloat32Auto(buf, conf.AppPpmConf.SmartRevRampTime)
	// ADC
	buf = append(buf, conf.AppAdcConf.CtrlType)
	buf = AppendFloat32Auto(buf, conf.AppAdcConf.Hyst)
	buf = AppendFloat16(buf, conf.AppAdcConf.VoltageStart, 1000)
	buf = AppendFloat16(buf, conf.AppAdcConf.VoltageEnd, 1000)
	buf = AppendFloat16(buf, conf.AppAdcConf.VoltageMin, 1000)
	buf = AppendFloat16(buf, conf.AppAdcConf.VoltageMax, 1000)
	buf = AppendFloat16(buf, conf.AppAdcConf.VoltageCenter, 1000)
	buf = AppendFloat16(buf, conf.AppAdcConf.Voltage2Start, 1000)
	buf = AppendFloat16(buf, conf.AppAdcConf.Voltage2End, 1000)
	buf = append(buf, conf.AppAdcConf.UseFilter)
	buf = append(buf, conf.AppAdcConf.SafeStart)
	buf = append(buf, conf.AppAdcConf.Buttons)
	buf = append(buf, conf.AppAdcConf.VoltageInverted)
	buf = append(buf, conf.AppAdcConf.Voltage2Inverted)
	buf = AppendFloat32Auto(buf, conf.AppAdcConf.ThrottleExp)
	buf = AppendFloat32Auto(buf, conf.AppAdcConf.ThrottleExpBrake)
	buf = append(buf, conf.AppAdcConf.ThrottleExpMode)
	buf = AppendFloat32Auto(buf, conf.AppAdcConf.RampTimePos)
	buf = AppendFloat32Auto(buf, conf.AppAdcConf.RampTimeNeg)
	buf = append(buf, conf.AppAdcConf.MultiEsc)
	buf = append(buf, conf.AppAdcConf.Tc)
	buf = AppendFloat32Auto(buf, conf.AppAdcConf.TcMaxDiff)
	buf = AppendUint16(buf, conf.AppAdcConf.UpdateRateHz)
	// UART
	buf = AppendUint32(buf, conf.AppUartBaudrate)
	// Chuk
	buf = append(buf, conf.AppChukConf.CtrlType)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.Hyst)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.RampTimePos)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.RampTimeNeg)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.StickErpmPerSInCc)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.ThrottleExp)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.ThrottleExpBrake)
	buf = append(buf, conf.AppChukConf.ThrottleExpMode)
	buf = append(buf, conf.AppChukConf.MultiEsc)
	buf = append(buf, conf.AppChukConf.Tc)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.TcMaxDiff)
	buf = append(buf, conf.AppChukConf.UseSmartRev)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.SmartRevMaxDuty)
	buf = AppendFloat32Auto(buf, conf.AppChukConf.SmartRevRampTime)
	// NRF
	buf = append(buf, conf.AppNrfConf.Speed)
	buf = append(buf, conf.AppNrfConf.Power)
	buf = append(buf, conf.AppNrfConf.CrcType)
	buf = append(buf, conf.AppNrfConf.RetryDelay)
	buf = append(buf, conf.AppNrfConf.Retries)
	buf = append(buf, conf.AppNrfConf.Channel)
	buf = append(buf, conf.AppNrfConf.Address[0])
	buf = append(buf, conf.AppNrfConf.Address[1])
	buf = append(buf, conf.AppNrfConf.Address[2])
	buf = append(buf, conf.AppNrfConf.SendCrcAck)
	// PAS
	buf = append(buf, conf.AppPasConf.CtrlType)
	buf = append(buf, conf.AppPasConf.SensorType)
	buf = AppendFloat16(buf, conf.AppPasConf.CurrentScaling, 1000)
	buf = AppendFloat16(buf, conf.AppPasConf.PedalRpmStart, 10)
	buf = AppendFloat16(buf, conf.AppPasConf.PedalRpmEnd, 10)
	buf = append(buf, conf.AppPasConf.InvertPedalDirection)
	buf = AppendUint16(buf, conf.AppPasConf.Magnets)
	buf = append(buf, conf.AppPasConf.UseFilter)
	buf = AppendFloat16(buf, conf.AppPasConf.RampTimePos, 100)
	buf = AppendFloat16(buf, conf.AppPasConf.RampTimeNeg, 100)
	buf = AppendUint16(buf, conf.AppPasConf.UpdateRateHz)
	// IMU
	buf = append(buf, conf.ImuConf.Type)
	buf = append(buf, conf.ImuConf.Mode)
	buf = append(buf, conf.ImuConf.Filter)
	buf = AppendFloat16(buf, conf.ImuConf.AccelLowpassFilterX, 1)
	buf = AppendFloat16(buf, conf.ImuConf.AccelLowpassFilterY, 1)
	buf = AppendFloat16(buf, conf.ImuConf.AccelLowpassFilterZ, 1)
	buf = AppendFloat16(buf, conf.ImuConf.GyroLowpassFilter, 1)
	buf = AppendUint16(buf, conf.ImuConf.SampleRateHz)
	buf = append(buf, conf.ImuConf.UseMagnetometer)
	buf = AppendFloat32Auto(buf, conf.ImuConf.AccelConfidenceDecay)
	buf = AppendFloat32Auto(buf, conf.ImuConf.MahonyKp)
	buf = AppendFloat32Auto(buf, conf.ImuConf.MahonyKi)
	buf = AppendFloat32Auto(buf, conf.ImuConf.MadgwickBeta)
	buf = AppendFloat32Auto(buf, conf.ImuConf.RotRoll)
	buf = AppendFloat32Auto(buf, conf.ImuConf.RotPitch)
	buf = AppendFloat32Auto(buf, conf.ImuConf.RotYaw)
	buf = AppendFloat32Auto(buf, conf.ImuConf.AccelOffsets[0])
	buf = AppendFloat32Auto(buf, conf.ImuConf.AccelOffsets[1])
	buf = AppendFloat32Auto(buf, conf.ImuConf.AccelOffsets[2])
	buf = AppendFloat32Auto(buf, conf.ImuConf.GyroOffsets[0])
	buf = AppendFloat32Auto(buf, conf.ImuConf.GyroOffsets[1])
	buf = AppendFloat32Auto(buf, conf.ImuConf.GyroOffsets[2])

	return buf
}

// DeserializeAppConf deserializes an AppConfiguration from bytes, matching the C
// confgenerator_deserialize_appconf function exactly.
func DeserializeAppConf(buf []byte) (*AppConfiguration, bool) {
	if len(buf) < 4 {
		return nil, false
	}
	ind := 0
	sig := GetUint32(buf, &ind)
	if sig != AppConfSignature {
		return nil, false
	}

	conf := &AppConfiguration{}
	conf.ControllerId = buf[ind]; ind++
	conf.TimeoutMsec = GetUint32(buf, &ind)
	conf.TimeoutBrakeCurrent = GetFloat32Auto(buf, &ind)
	conf.CanStatusRate1 = GetUint16(buf, &ind)
	conf.CanStatusRate2 = GetUint16(buf, &ind)
	conf.CanStatusMsgsR1 = buf[ind]; ind++
	conf.CanStatusMsgsR2 = buf[ind]; ind++
	conf.CanBaudRate = buf[ind]; ind++
	conf.PairingDone = buf[ind]; ind++
	conf.PermanentUartEnabled = buf[ind]; ind++
	conf.ShutdownMode = buf[ind]; ind++
	conf.CanMode = buf[ind]; ind++
	conf.UavcanEscIndex = buf[ind]; ind++
	conf.UavcanRawMode = buf[ind]; ind++
	conf.UavcanRawRpmMax = GetFloat32Auto(buf, &ind)
	conf.UavcanStatusCurrentMode = buf[ind]; ind++
	conf.ServoOutEnable = buf[ind]; ind++
	conf.KillSwMode = buf[ind]; ind++
	conf.AppToUse = buf[ind]; ind++
	// PPM
	conf.AppPpmConf.CtrlType = buf[ind]; ind++
	conf.AppPpmConf.PidMaxErpm = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.Hyst = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.PulseStart = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.PulseEnd = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.PulseCenter = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.MedianFilter = buf[ind]; ind++
	conf.AppPpmConf.SafeStart = buf[ind]; ind++
	conf.AppPpmConf.ThrottleExp = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.ThrottleExpBrake = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.ThrottleExpMode = buf[ind]; ind++
	conf.AppPpmConf.RampTimePos = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.RampTimeNeg = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.MultiEsc = buf[ind]; ind++
	conf.AppPpmConf.Tc = buf[ind]; ind++
	conf.AppPpmConf.TcMaxDiff = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.MaxErpmForDir = GetFloat16(buf, 1, &ind)
	conf.AppPpmConf.SmartRevMaxDuty = GetFloat32Auto(buf, &ind)
	conf.AppPpmConf.SmartRevRampTime = GetFloat32Auto(buf, &ind)
	// ADC
	conf.AppAdcConf.CtrlType = buf[ind]; ind++
	conf.AppAdcConf.Hyst = GetFloat32Auto(buf, &ind)
	conf.AppAdcConf.VoltageStart = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.VoltageEnd = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.VoltageMin = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.VoltageMax = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.VoltageCenter = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.Voltage2Start = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.Voltage2End = GetFloat16(buf, 1000, &ind)
	conf.AppAdcConf.UseFilter = buf[ind]; ind++
	conf.AppAdcConf.SafeStart = buf[ind]; ind++
	conf.AppAdcConf.Buttons = buf[ind]; ind++
	conf.AppAdcConf.VoltageInverted = buf[ind]; ind++
	conf.AppAdcConf.Voltage2Inverted = buf[ind]; ind++
	conf.AppAdcConf.ThrottleExp = GetFloat32Auto(buf, &ind)
	conf.AppAdcConf.ThrottleExpBrake = GetFloat32Auto(buf, &ind)
	conf.AppAdcConf.ThrottleExpMode = buf[ind]; ind++
	conf.AppAdcConf.RampTimePos = GetFloat32Auto(buf, &ind)
	conf.AppAdcConf.RampTimeNeg = GetFloat32Auto(buf, &ind)
	conf.AppAdcConf.MultiEsc = buf[ind]; ind++
	conf.AppAdcConf.Tc = buf[ind]; ind++
	conf.AppAdcConf.TcMaxDiff = GetFloat32Auto(buf, &ind)
	conf.AppAdcConf.UpdateRateHz = GetUint16(buf, &ind)
	// UART
	conf.AppUartBaudrate = GetUint32(buf, &ind)
	// Chuk
	conf.AppChukConf.CtrlType = buf[ind]; ind++
	conf.AppChukConf.Hyst = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.RampTimePos = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.RampTimeNeg = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.StickErpmPerSInCc = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.ThrottleExp = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.ThrottleExpBrake = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.ThrottleExpMode = buf[ind]; ind++
	conf.AppChukConf.MultiEsc = buf[ind]; ind++
	conf.AppChukConf.Tc = buf[ind]; ind++
	conf.AppChukConf.TcMaxDiff = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.UseSmartRev = buf[ind]; ind++
	conf.AppChukConf.SmartRevMaxDuty = GetFloat32Auto(buf, &ind)
	conf.AppChukConf.SmartRevRampTime = GetFloat32Auto(buf, &ind)
	// NRF
	conf.AppNrfConf.Speed = buf[ind]; ind++
	conf.AppNrfConf.Power = buf[ind]; ind++
	conf.AppNrfConf.CrcType = buf[ind]; ind++
	conf.AppNrfConf.RetryDelay = buf[ind]; ind++
	conf.AppNrfConf.Retries = buf[ind]; ind++
	conf.AppNrfConf.Channel = buf[ind]; ind++
	conf.AppNrfConf.Address[0] = buf[ind]; ind++
	conf.AppNrfConf.Address[1] = buf[ind]; ind++
	conf.AppNrfConf.Address[2] = buf[ind]; ind++
	conf.AppNrfConf.SendCrcAck = buf[ind]; ind++
	// PAS
	conf.AppPasConf.CtrlType = buf[ind]; ind++
	conf.AppPasConf.SensorType = buf[ind]; ind++
	conf.AppPasConf.CurrentScaling = GetFloat16(buf, 1000, &ind)
	conf.AppPasConf.PedalRpmStart = GetFloat16(buf, 10, &ind)
	conf.AppPasConf.PedalRpmEnd = GetFloat16(buf, 10, &ind)
	conf.AppPasConf.InvertPedalDirection = buf[ind]; ind++
	conf.AppPasConf.Magnets = GetUint16(buf, &ind)
	conf.AppPasConf.UseFilter = buf[ind]; ind++
	conf.AppPasConf.RampTimePos = GetFloat16(buf, 100, &ind)
	conf.AppPasConf.RampTimeNeg = GetFloat16(buf, 100, &ind)
	conf.AppPasConf.UpdateRateHz = GetUint16(buf, &ind)
	// IMU
	conf.ImuConf.Type = buf[ind]; ind++
	conf.ImuConf.Mode = buf[ind]; ind++
	conf.ImuConf.Filter = buf[ind]; ind++
	conf.ImuConf.AccelLowpassFilterX = GetFloat16(buf, 1, &ind)
	conf.ImuConf.AccelLowpassFilterY = GetFloat16(buf, 1, &ind)
	conf.ImuConf.AccelLowpassFilterZ = GetFloat16(buf, 1, &ind)
	conf.ImuConf.GyroLowpassFilter = GetFloat16(buf, 1, &ind)
	conf.ImuConf.SampleRateHz = GetUint16(buf, &ind)
	conf.ImuConf.UseMagnetometer = buf[ind]; ind++
	conf.ImuConf.AccelConfidenceDecay = GetFloat32Auto(buf, &ind)
	conf.ImuConf.MahonyKp = GetFloat32Auto(buf, &ind)
	conf.ImuConf.MahonyKi = GetFloat32Auto(buf, &ind)
	conf.ImuConf.MadgwickBeta = GetFloat32Auto(buf, &ind)
	conf.ImuConf.RotRoll = GetFloat32Auto(buf, &ind)
	conf.ImuConf.RotPitch = GetFloat32Auto(buf, &ind)
	conf.ImuConf.RotYaw = GetFloat32Auto(buf, &ind)
	conf.ImuConf.AccelOffsets[0] = GetFloat32Auto(buf, &ind)
	conf.ImuConf.AccelOffsets[1] = GetFloat32Auto(buf, &ind)
	conf.ImuConf.AccelOffsets[2] = GetFloat32Auto(buf, &ind)
	conf.ImuConf.GyroOffsets[0] = GetFloat32Auto(buf, &ind)
	conf.ImuConf.GyroOffsets[1] = GetFloat32Auto(buf, &ind)
	conf.ImuConf.GyroOffsets[2] = GetFloat32Auto(buf, &ind)

	return conf, true
}

// boolByte converts a bool to uint8 (1 or 0), matching C true/false.
func boolByte(b bool) uint8 {
	if b {
		return 1
	}
	return 0
}

// DefaultMCConf returns an MCConfiguration with defaults matching
// confgenerator_set_defaults_mcconf from VESC FW 6.05.
// Enum values are resolved to their numeric equivalents.
func DefaultMCConf() *MCConfiguration {
	conf := &MCConfiguration{}

	// pwm_mode: PWM_MODE_SYNCHRONOUS = 1
	conf.PwmMode = 1
	// comm_mode: COMM_MODE_INTEGRATE = 0
	conf.CommMode = 0
	// motor_type: MOTOR_TYPE_FOC = 2
	conf.MotorType = 2
	// sensor_mode: SENSOR_MODE_SENSORLESS = 0
	conf.SensorMode = 0

	conf.LCurrentMax = 60.0
	conf.LCurrentMin = -60.0
	conf.LInCurrentMax = 99.0
	conf.LInCurrentMin = -60.0
	conf.LInCurrentMapStart = 1.0
	conf.LInCurrentMapFilter = 0.005
	conf.LAbsCurrentMax = 130.0
	conf.LMinErpm = -100000.0
	conf.LMaxErpm = 100000.0
	conf.LErpmStart = 0.8
	conf.LMaxErpmFbrake = 300
	conf.LMaxErpmFbrakeCc = 1500
	conf.LMinVin = 8.0
	conf.LMaxVin = 57.0
	conf.LBatteryCutStart = 10.0
	conf.LBatteryCutEnd = 8.0
	conf.LBatteryRegenCutStart = 1000.0
	conf.LBatteryRegenCutEnd = 1100.0
	// l_slow_abs_current: false = 0
	conf.LSlowAbsCurrent = 0
	// l_temp_fet_start: 85.0 cast to uint8 = 85
	conf.LTempFetStart = 85
	// l_temp_fet_end: 100.0 cast to uint8 = 100
	conf.LTempFetEnd = 100
	// l_temp_motor_start: 85.0
	conf.LTempMotorStart = 85
	// l_temp_motor_end: 100.0
	conf.LTempMotorEnd = 100
	conf.LTempAccelDec = 0.15
	conf.LMinDuty = 0.005
	conf.LMaxDuty = 0.95
	conf.LWattMax = 1500000.0
	conf.LWattMin = -1500000.0
	conf.LCurrentMaxScale = 1.0
	conf.LCurrentMinScale = 1.0
	conf.LDutyStart = 1.0

	conf.SlMinErpm = 150
	conf.SlMinErpmCycleIntLimit = 1100.0
	conf.SlMaxFullbreakCurrentDirChange = 10.0
	conf.SlCycleIntLimit = 62.0
	conf.SlPhaseAdvanceAtBr = 0.8
	conf.SlCycleIntRpmBr = 80000.0
	conf.SlBemfCouplingK = 600.0

	// hall_table: -1,1,3,2,5,6,4,-1 (int8 -> uint8: -1=255)
	conf.HallTable = [8]uint8{255, 1, 3, 2, 5, 6, 4, 255}
	conf.HallSlErpm = 2000.0

	conf.FocCurrentKp = 0.03
	conf.FocCurrentKi = 50.0
	conf.FocFZv = 25000.0
	conf.FocDtUs = 0.12
	// foc_encoder_inverted: false = 0
	conf.FocEncoderInverted = 0
	conf.FocEncoderOffset = 180.0
	conf.FocEncoderRatio = 7.0
	// foc_sensor_mode: FOC_SENSOR_MODE_SENSORLESS = 0
	conf.FocSensorMode = 0
	conf.FocPllKp = 2000.0
	conf.FocPllKi = 30000.0
	conf.FocMotorL = 0.000007
	conf.FocMotorLdLqDiff = 0.0
	conf.FocMotorR = 0.015
	conf.FocMotorFluxLinkage = 0.00245
	conf.FocObserverGain = 9e7
	conf.FocObserverGainSlow = 0.05
	conf.FocObserverOffset = -1.0
	conf.FocDutyDowmrampKp = 50.0
	conf.FocDutyDowmrampKi = 1000.0
	conf.FocStartCurrDec = 1.0
	conf.FocStartCurrDecRpm = 2500.0
	conf.FocOpenloopRpm = 1500.0
	conf.FocOpenloopRpmLow = 0.0
	conf.FocDGainScaleStart = 0.9
	conf.FocDGainScaleMaxMod = 0.2
	conf.FocSlOpenloopHyst = 0.1
	conf.FocSlOpenloopTimeLock = 0.0
	conf.FocSlOpenloopTimeRamp = 0.1
	conf.FocSlOpenloopTime = 0.05
	conf.FocSlOpenloopBoostQ = 0.0
	conf.FocSlOpenloopMaxQ = -1.0
	// foc_hall_table: all 255
	conf.FocHallTable = [8]uint8{255, 255, 255, 255, 255, 255, 255, 255}
	conf.FocHallInterpErpm = 500
	conf.FocSlErpmStart = 2500.0
	conf.FocSlErpm = 3500.0
	// foc_control_sample_mode: FOC_CONTROL_SAMPLE_MODE_V0 = 0
	conf.FocControlSampleMode = 0
	// foc_current_sample_mode: FOC_CURRENT_SAMPLE_MODE_LONGEST_ZERO = 0
	conf.FocCurrentSampleMode = 0
	// foc_sat_comp_mode: SAT_COMP_DISABLED = 0
	conf.FocSatCompMode = 0
	conf.FocSatComp = 0.0
	// foc_temp_comp: false = 0
	conf.FocTempComp = 0
	conf.FocTempCompBaseTemp = 25.0
	conf.FocCurrentFilterConst = 0.1
	// foc_cc_decoupling: FOC_CC_DECOUPLING_DISABLED = 0
	conf.FocCcDecoupling = 0
	// foc_observer_type: FOC_OBSERVER_MXLEMMING_LAMBDA_COMP = 3
	conf.FocObserverType = 3
	conf.FocHfiVoltageStart = 20
	conf.FocHfiVoltageRun = 4
	conf.FocHfiVoltageMax = 6
	conf.FocHfiGain = 0.3
	conf.FocHfiMaxErr = 0.15
	conf.FocHfiHyst = 0.0
	conf.FocSlErpmHfi = 3000.0
	conf.FocHfiStartSamples = 5
	conf.FocHfiObsOvrSec = 0.001
	// foc_hfi_samples: HFI_SAMPLES_16 = 1
	conf.FocHfiSamples = 1
	// foc_offsets_cal_on_boot: true = 1
	conf.FocOffsetsCalOnBoot = 1
	conf.FocOffsetsCurrent = [3]float64{2048.0, 2048.0, 2048.0}
	conf.FocOffsetsVoltage = [3]float64{0.0, 0.0, 0.0}
	conf.FocOffsetsVoltageUndriven = [3]float64{0.0, 0.0, 0.0}
	// foc_phase_filter_enable: true = 1
	conf.FocPhaseFilterEnable = 1
	// foc_phase_filter_disable_fault: true = 1
	conf.FocPhaseFilterDisableFault = 1
	conf.FocPhaseFilterMaxErpm = 4000.0
	// foc_mtpa_mode: MTPA_MODE_OFF = 0
	conf.FocMtpaMode = 0
	conf.FocFwCurrentMax = 0.0
	conf.FocFwDutyStart = 0.9
	conf.FocFwRampTime = 0.2
	conf.FocFwQCurrentFactor = 0.02
	// foc_speed_soure: FOC_SPEED_SRC_CORRECTED = 0
	conf.FocSpeedSoure = 0
	// foc_short_ls_on_zero_duty: false = 0
	conf.FocShortLsOnZeroDuty = 0

	// sp_pid_loop_rate: PID_RATE_1000_HZ = 5
	conf.SpPidLoopRate = 5
	conf.SPidKp = 0.004
	conf.SPidKi = 0.004
	conf.SPidKd = 0.0001
	conf.SPidKdFilter = 0.2
	conf.SPidMinErpm = 900.0
	// s_pid_allow_braking: true = 1
	conf.SPidAllowBraking = 1
	conf.SPidRampErpmsS = 25000.0
	// s_pid_speed_source: S_PID_SPEED_SRC_PLL = 0
	conf.SPidSpeedSource = 0

	conf.PPidKp = 0.025
	conf.PPidKi = 0.0
	conf.PPidKd = 0.0
	conf.PPidKdProc = 0.00035
	conf.PPidKdFilter = 0.2
	conf.PPidAngDiv = 1.0
	conf.PPidGainDecAngle = 0.0
	conf.PPidOffset = 0.0

	conf.CcStartupBoostDuty = 0.01
	conf.CcMinCurrent = 0.05
	conf.CcGain = 0.0046
	conf.CcRampStepMax = 0.04

	conf.MFaultStopTimeMs = 500
	conf.MDutyRampStep = 0.02
	conf.MCurrentBackoffGain = 0.5
	conf.MEncoderCounts = 8192
	conf.MEncoderSinAmp = 1.0
	conf.MEncoderCosAmp = 1.0
	conf.MEncoderSinOffset = 1.65
	conf.MEncoderCosOffset = 1.65
	conf.MEncoderSincosFilterConstant = 0.5
	conf.MEncoderSincosPhaseCorrection = 0.0
	// m_sensor_port_mode: SENSOR_PORT_MODE_HALL = 0
	conf.MSensorPortMode = 0
	// m_invert_direction: false = 0
	conf.MInvertDirection = 0
	// m_drv8301_oc_mode: DRV8301_OC_LIMIT = 0
	conf.MDrv8301OcMode = 0
	conf.MDrv8301OcAdj = 16
	conf.MBldcFSwMin = 3000
	conf.MBldcFSwMax = 35000
	conf.MDcFSw = 25000
	conf.MNtcMotorBeta = 3380.0
	// m_out_aux_mode: OUT_AUX_MODE_OFF = 0
	conf.MOutAuxMode = 0
	// m_motor_temp_sens_type: TEMP_SENSOR_NTC_10K_25C = 0
	conf.MMotorTempSensType = 0
	conf.MPtcMotorCoeff = 0.61
	conf.MNtcxPtcxRes = 10000.0
	conf.MNtcxPtcxTempBase = 25.0
	conf.MHallExtraSamples = 3
	conf.MBattFilterConst = 45

	conf.SiMotorPoles = 14
	conf.SiGearRatio = 3
	conf.SiWheelDiameter = 0.083
	// si_battery_type: BATTERY_TYPE_LIION_3_0__4_2 = 0
	conf.SiBatteryType = 0
	conf.SiBatteryCells = 3
	conf.SiBatteryAh = 6.0
	conf.SiMotorNlCurrent = 1.0

	// bms.type: BMS_TYPE_VESC = 1
	conf.BmsType = 1
	conf.BmsLimitMode = 3
	conf.BmsTLimitStart = 45
	conf.BmsTLimitEnd = 65
	conf.BmsSocLimitStart = 0.05
	conf.BmsSocLimitEnd = 0
	conf.BmsVminLimitStart = 2.9
	conf.BmsVminLimitEnd = 2.5
	conf.BmsVmaxLimitStart = 4.2
	conf.BmsVmaxLimitEnd = 4.3
	// bms.fwd_can_mode: BMS_FWD_CAN_MODE_DISABLED = 0
	conf.BmsFwdCanMode = 0

	return conf
}

// DefaultAppConf returns an AppConfiguration with defaults matching
// confgenerator_set_defaults_appconf from VESC FW 6.05.
// Enum values are resolved to their numeric equivalents.
func DefaultAppConf() *AppConfiguration {
	conf := &AppConfiguration{}

	// controller_id: HW_DEFAULT_ID depends on hardware UUID; use 0 as generic default
	conf.ControllerId = 0
	conf.TimeoutMsec = 1000
	conf.TimeoutBrakeCurrent = 0.0
	conf.CanStatusRate1 = 50
	conf.CanStatusRate2 = 5
	conf.CanStatusMsgsR1 = 0
	conf.CanStatusMsgsR2 = 0
	// can_baud_rate: CAN_BAUD_500K = 2
	conf.CanBaudRate = 2
	// pairing_done: false = 0
	conf.PairingDone = 0
	// permanent_uart_enabled: true = 1
	conf.PermanentUartEnabled = 1
	// shutdown_mode: SHUTDOWN_MODE_OFF_AFTER_30M = 7
	conf.ShutdownMode = 7
	// can_mode: CAN_MODE_VESC = 0
	conf.CanMode = 0
	conf.UavcanEscIndex = 0
	// uavcan_raw_mode: UAVCAN_RAW_MODE_CURRENT = 0
	conf.UavcanRawMode = 0
	conf.UavcanRawRpmMax = 50000.0
	// uavcan_status_current_mode: UAVCAN_STATUS_CURRENT_MODE_MOTOR = 0
	conf.UavcanStatusCurrentMode = 0
	// servo_out_enable: false = 0
	conf.ServoOutEnable = 0
	// kill_sw_mode: KILL_SW_MODE_DISABLED = 0
	conf.KillSwMode = 0
	// app_to_use: APP_UART = 3
	conf.AppToUse = 3

	// PPM defaults
	// ctrl_type: PPM_CTRL_TYPE_NONE = 0
	conf.AppPpmConf.CtrlType = 0
	conf.AppPpmConf.PidMaxErpm = 15000
	conf.AppPpmConf.Hyst = 0.15
	conf.AppPpmConf.PulseStart = 1.0
	conf.AppPpmConf.PulseEnd = 2.0
	conf.AppPpmConf.PulseCenter = 1.5
	// median_filter: true = 1
	conf.AppPpmConf.MedianFilter = 1
	// safe_start: true = 1
	conf.AppPpmConf.SafeStart = 1
	conf.AppPpmConf.ThrottleExp = 0.0
	conf.AppPpmConf.ThrottleExpBrake = 0.0
	// throttle_exp_mode: THR_EXP_POLY = 2
	conf.AppPpmConf.ThrottleExpMode = 2
	conf.AppPpmConf.RampTimePos = 0.4
	conf.AppPpmConf.RampTimeNeg = 0.2
	// multi_esc: true = 1
	conf.AppPpmConf.MultiEsc = 1
	// tc: false = 0
	conf.AppPpmConf.Tc = 0
	conf.AppPpmConf.TcMaxDiff = 3000.0
	conf.AppPpmConf.MaxErpmForDir = 4000.0
	conf.AppPpmConf.SmartRevMaxDuty = 0.07
	conf.AppPpmConf.SmartRevRampTime = 3.0

	// ADC defaults
	// ctrl_type: ADC_CTRL_TYPE_NONE = 0
	conf.AppAdcConf.CtrlType = 0
	conf.AppAdcConf.Hyst = 0.15
	conf.AppAdcConf.VoltageStart = 0.9
	conf.AppAdcConf.VoltageEnd = 3.0
	conf.AppAdcConf.VoltageMin = 0.0
	conf.AppAdcConf.VoltageMax = 3.5
	conf.AppAdcConf.VoltageCenter = 2.0
	conf.AppAdcConf.Voltage2Start = 0.9
	conf.AppAdcConf.Voltage2End = 3.0
	// use_filter: true = 1
	conf.AppAdcConf.UseFilter = 1
	// safe_start: true = 1
	conf.AppAdcConf.SafeStart = 1
	conf.AppAdcConf.Buttons = 0
	// voltage_inverted: false = 0
	conf.AppAdcConf.VoltageInverted = 0
	// voltage2_inverted: false = 0
	conf.AppAdcConf.Voltage2Inverted = 0
	conf.AppAdcConf.ThrottleExp = 0.0
	conf.AppAdcConf.ThrottleExpBrake = 0.0
	// throttle_exp_mode: THR_EXP_POLY = 2
	conf.AppAdcConf.ThrottleExpMode = 2
	conf.AppAdcConf.RampTimePos = 0.3
	conf.AppAdcConf.RampTimeNeg = 0.1
	// multi_esc: true = 1
	conf.AppAdcConf.MultiEsc = 1
	// tc: false = 0
	conf.AppAdcConf.Tc = 0
	conf.AppAdcConf.TcMaxDiff = 3000.0
	conf.AppAdcConf.UpdateRateHz = 500

	conf.AppUartBaudrate = 115200

	// Chuk defaults
	// ctrl_type: CHUK_CTRL_TYPE_NONE = 0
	conf.AppChukConf.CtrlType = 0
	conf.AppChukConf.Hyst = 0.15
	conf.AppChukConf.RampTimePos = 0.4
	conf.AppChukConf.RampTimeNeg = 0.2
	conf.AppChukConf.StickErpmPerSInCc = 3000.0
	conf.AppChukConf.ThrottleExp = 0.0
	conf.AppChukConf.ThrottleExpBrake = 0.0
	// throttle_exp_mode: THR_EXP_POLY = 2
	conf.AppChukConf.ThrottleExpMode = 2
	// multi_esc: true = 1
	conf.AppChukConf.MultiEsc = 1
	// tc: false = 0
	conf.AppChukConf.Tc = 0
	conf.AppChukConf.TcMaxDiff = 3000.0
	// use_smart_rev: true = 1
	conf.AppChukConf.UseSmartRev = 1
	conf.AppChukConf.SmartRevMaxDuty = 0.07
	conf.AppChukConf.SmartRevRampTime = 3.0

	// NRF defaults
	// speed: NRF_SPEED_1M = 1
	conf.AppNrfConf.Speed = 1
	// power: NRF_POWER_0DBM = 3
	conf.AppNrfConf.Power = 3
	// crc_type: NRF_CRC_1B = 1
	conf.AppNrfConf.CrcType = 1
	// retry_delay: NRF_RETR_DELAY_250US = 0
	conf.AppNrfConf.RetryDelay = 0
	conf.AppNrfConf.Retries = 3
	conf.AppNrfConf.Channel = 76
	conf.AppNrfConf.Address = [3]uint8{0xC6, 0xC7, 0x00}
	// send_crc_ack: true = 1
	conf.AppNrfConf.SendCrcAck = 1

	// PAS defaults
	// ctrl_type: PAS_CTRL_TYPE_NONE = 0
	conf.AppPasConf.CtrlType = 0
	// sensor_type: PAS_SENSOR_TYPE_QUADRATURE = 0
	conf.AppPasConf.SensorType = 0
	conf.AppPasConf.CurrentScaling = 0.1
	conf.AppPasConf.PedalRpmStart = 10.0
	conf.AppPasConf.PedalRpmEnd = 180.0
	// invert_pedal_direction: false = 0
	conf.AppPasConf.InvertPedalDirection = 0
	conf.AppPasConf.Magnets = 24
	// use_filter: true = 1
	conf.AppPasConf.UseFilter = 1
	conf.AppPasConf.RampTimePos = 0.6
	conf.AppPasConf.RampTimeNeg = 0.3
	conf.AppPasConf.UpdateRateHz = 500

	// IMU defaults
	// type: IMU_TYPE_INTERNAL = 1
	conf.ImuConf.Type = 1
	// mode: AHRS_MODE_MADGWICK = 0
	conf.ImuConf.Mode = 0
	// filter: IMU_FILTER_MEDIUM = 1
	conf.ImuConf.Filter = 1
	conf.ImuConf.AccelLowpassFilterX = 0.0
	conf.ImuConf.AccelLowpassFilterY = 0.0
	conf.ImuConf.AccelLowpassFilterZ = 0.0
	conf.ImuConf.GyroLowpassFilter = 0.0
	conf.ImuConf.SampleRateHz = 200
	// use_magnetometer: true = 1
	conf.ImuConf.UseMagnetometer = 1
	conf.ImuConf.AccelConfidenceDecay = 1.0
	conf.ImuConf.MahonyKp = 0.3
	conf.ImuConf.MahonyKi = 0.0
	conf.ImuConf.MadgwickBeta = 0.1
	conf.ImuConf.RotRoll = 0.0
	conf.ImuConf.RotPitch = 0.0
	conf.ImuConf.RotYaw = 0.0
	conf.ImuConf.AccelOffsets = [3]float64{0.0, 0.0, 0.0}
	conf.ImuConf.GyroOffsets = [3]float64{0.0, 0.0, 0.0}

	return conf
}
